### ISSUE TITLE
Need help getting email id after bind

### ISSUE THREAD

**Issue by madhan5000** [etyp/meteor-accounts-ldap#27]
@etyp Thank you for this package. I am trying to use this with Telescope app. I am able to authenticate against our ldap server but I need help getting email id after authentication. 

My app crashes with

`SizeLimitExceededError: Size Limit Exceeded`

 when I enable this on the **server**

`    LDAP_DEFAULTS.searchResultsProfileMap = [
        {
            resultKey: 'cn',
            profileProperty: 'displayName'
        }
        ,{
            resultKey: 'mail',
            profileProperty: 'email'
        }
    ]
`

**Client code**
`  
 Meteor.loginWithLDAP(employeeId,password,{dn:employeeId+'@' +domain,search: '(objectclass=*)'},function(err,result){
        if(err)console.log(err);
    });
`

**Error**

`
W20161109-13:17:11.771(-5)? (STDERR) 
W20161109-13:17:11.771(-5)? (STDERR) events.js:141
W20161109-13:17:11.772(-5)? (STDERR)       throw er; // Unhandled 'error' event
W20161109-13:17:11.772(-5)? (STDERR)       ^
W20161109-13:17:11.773(-5)? (STDERR) SizeLimitExceededError: Size Limit Exceeded
W20161109-13:17:11.773(-5)? (STDERR)     at messageCallback (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:867:40)
W20161109-13:17:11.774(-5)? (STDERR)     at Parser.onMessage (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:199:12)
W20161109-13:17:11.774(-5)? (STDERR)     at emitOne (events.js:77:13)
W20161109-13:17:11.774(-5)? (STDERR)     at Parser.emit (events.js:169:7)
W20161109-13:17:11.774(-5)? (STDERR)     at Parser.write (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:105:8)
W20161109-13:17:11.774(-5)? (STDERR)     at end (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:71:19)
W20161109-13:17:11.774(-5)? (STDERR)     at Parser.write (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/messages/parser.js:107:10)
W20161109-13:17:11.775(-5)? (STDERR)     at Socket.onData (/Users/163106/.meteor/packages/typ_ldapjs/.0.7.3.6gl79l++os+web.browser+web.cordova/npm/node_modules/ldapjs/lib/client/client.js:155:24)
W20161109-13:17:11.775(-5)? (STDERR)     at emitOne (events.js:77:13)
W20161109-13:17:11.775(-5)? (STDERR)     at Socket.emit (events.js:169:7)
`

**Comment by madhan5000** [comment]
this is a duplicate of this issue https://github.com/etyp/meteor-accounts-ldap/issues/18
